# Generated by Django 5.1.4 on 2024-12-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=50)),
                ('tipo_dispositivo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('activo_viejo', models.CharField(max_length=25, unique=True)),
                ('activo_nuevo', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontic.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(choices=[('falla', 'Falla'), ('error', 'Error'), ('mejora', 'Mejora'), ('agregar funcion', 'Agregar Funcion')], max_length=100)),
                ('requerimiento', models.CharField(max_length=200)),
                ('solucion', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha_servicio')),
                ('dispositivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontic.dispositivo')),
            ],
        ),
    ]
